### ISSUE TITLE
Website and REST API appear down

### ISSUE THREAD

**Issue by neksa** [udel-cbcb/pyiPTMnet#5]
SSL protocol error while accessing research.bioinformatics.udel.edu
```
SSLError: HTTPSConnectionPool(host='research.bioinformatics.udel.edu', port=443): Max retries exceeded with url: /iptmnet/api/v1/Q15796/info (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1125)')))
```

Accessing iPTMNet API via any browser gives the same error.

**Comment by Sachinx0e** [comment]
Hi @neksa, can you check again now. I have restarted the database container and it should be working. Also just a heads up, the API will be unavailable on Friday as we are in the process of physically migrating our servers to a new data-center.

**Comment by neksa** [comment]
@Sachinx0e looking good now! Thanks for fixing and for the heads up!
